// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcKSvAVCE8o1U4lvZunZk3vw4V6tf07Bo',
    appId: '1:655317573196:web:c7e8288532a4605bef9ee9',
    messagingSenderId: '655317573196',
    projectId: 'mynotes-45f5b',
    authDomain: 'mynotes-45f5b.firebaseapp.com',
    storageBucket: 'mynotes-45f5b.appspot.com',
    measurementId: 'G-R0BM9T8VN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBvNLZ6v-Mo3qQRXrJSZi3KHnbhHT6j2o',
    appId: '1:655317573196:android:59f656907dc34befef9ee9',
    messagingSenderId: '655317573196',
    projectId: 'mynotes-45f5b',
    storageBucket: 'mynotes-45f5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfdKzDwcqvrVOAwDGBm7_JUb2DX1F1CqE',
    appId: '1:655317573196:ios:2136cd1e9ef061b9ef9ee9',
    messagingSenderId: '655317573196',
    projectId: 'mynotes-45f5b',
    storageBucket: 'mynotes-45f5b.appspot.com',
    iosBundleId: 'com.testapp.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfdKzDwcqvrVOAwDGBm7_JUb2DX1F1CqE',
    appId: '1:655317573196:ios:314da8dfdd97d41bef9ee9',
    messagingSenderId: '655317573196',
    projectId: 'mynotes-45f5b',
    storageBucket: 'mynotes-45f5b.appspot.com',
    iosBundleId: 'com.testapp.mynotes.RunnerTests',
  );
}
